{% set name = "geemap" %}
{% set version = "0.35.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98f3f17fb1d07a6fe43b06f03fb680e10517adfd96002184015a3d4fe92435d6

build:
  number: 1
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - bqplot
    - colour
    - earthengine-api >=1.0.0
    - eerepr >=0.0.4
    - ee_extra >=0.0.15
    - ffmpeg-python
    - folium >=0.13.0
    - gdown
    - geeadd >=0.5.1
    - geocoder
    - geojson
    - ipyevents
    - ipyfilechooser >=0.6.0
    - ipyleaflet >=0.17.0
    - ipytree
    - ipywidgets
    - jupyterlab
    - matplotlib-base
    - numpy
    - pandas
    - pillow
    - pycrs
    - pyperclip
    - pyshp >=2.1.3
    - python >={{ python_min }}
    - python-box
    - sankee
    - scooby
    - whiteboxgui >=0.6.0
    - xyzservices

test:
  imports:
    - geemap
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://geemap.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Earth Engine Python API and interactive mapping
  description: A Python package for interactive geospatial analysis and visualization with Google Earth Engine.
  doc_url: https://geemap.org
  dev_url: https://github.com/gee-community/geemap

extra:
  recipe-maintainers:
    - giswqs
    - jdbcode
    - naschmitz
