{% set name = "geemap" %}
{% set version = "0.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d61a5567454e7f4684c8d53f1f500913d1a7048ada3c1cfad60c1446600acdd9

build:
  number: 0
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bqplot
    - colour
    - earthengine-api >=0.1.347
    - eerepr >=0.0.4
    - ee_extra >=0.0.15
    - ffmpeg-python
    - folium >=0.13.0
    - gdown
    - geeadd >=0.5.1
    - geocoder
    - geojson
    - ipyevents
    - ipyfilechooser >=0.6.0
    - ipyleaflet >=0.17.0,<0.19.0
    - ipytree
    - ipywidgets
    - jupyterlab
    - matplotlib-base
    - numpy
    - pandas
    - pillow
    - pycrs
    - pyperclip
    - pyshp >=2.1.3
    - python >=3.8
    - python-box
    - sankee
    - scooby
    - whiteboxgui >=0.6.0
    - xyzservices

test:
  imports:
    - geemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geemap.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Earth Engine Python API and interactive mapping
  description: A Python package for interactive mapping with Google Earth Engine, ipyleaflet, and folium.
  doc_url: https://geemap.org
  dev_url: https://github.com/gee-community/geemap

extra:
  recipe-maintainers:
    - giswqs
    - jdbcode
    - naschmitz
