{% set name = "geemap" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3c4208c97feb659c2a7c3c4eab5211c64a0c6daa78319108f8f4e1324e52a29e

build:
  number: 1
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - bqplot
    - click
    - colour
    - dulwich
    - earthengine-api
    - folium >=0.11.0
    - geeadd
    - geocoder
    - ipyfilechooser
    - ipyleaflet >=0.12.6
    - ipynb-py-convert
    - ipytree
    - matplotlib-base
    - mss
    - pillow
    - pyshp
    - python
    - pip

test:
  imports:
    - geemap
  commands:
    - geemap --help

about:
  home: "https://github.com/giswqs/geemap"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping using Google Earth Engine and ipyleaflet"
  doc_url: https://geemap.readthedocs.io
  dev_url: https://github.com/giswqs/geemap

extra:
  recipe-maintainers:
    - giswqs
